[build]
  publish = "dist"

[[redirects]]
  from = "/pt-br/*"
  to = "/pt-br/:splat"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/pt-br/"
  status = 302
