[build]
  publish = "dist/portfolio-website/browser"

[[redirects]]
  from = "/pt/*"
  to = "/pt/:splat"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/pt/"
  status = 302
